name: EdgeWARN-dev
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - cfgrib
  - beautifulsoup4
  - numpy
  - requests
  - scikit-image
  - scipy
  - shapely
  - xarray
  - folium
  - pip:
    - PyQt6
    - PyQt6-WebEngine
